name: haskell-in-depth
version: 1.0
author: Arjun Kathuria
extra-source-files:
  - package.yaml

tested-with: GHC == 8.10.3, GHC == 8.10.4

dependencies: base >= 4.14 && <4.15

executables:
  vocab1:
    source-dirs: chapter_01
    main: vocab.hs
    dependencies:
      - text >=1.2 && <1.3
  vocab2:
    source-dirs: chapter_01
    main: vocab2.hs
    dependencies:
      - text >=1.2 && <1.3
  vocab3:
    source-dirs: chapter_01
    main: vocab3.hs
    dependencies:
    - text >=1.2 && <1.3
    - fmt >= 0.6 && <0.7

  radar:
    source-dirs: chapter_02/radar
    main: Main.hs
    other-modules: Radar
    other-extensions:
      - DeriveAnyClass
    dependencies:
      - fmt >=0.5 && <0.7

  # Chapter 5
  reader:
    source-dirs: chapter_05
    main: reader.hs
    other-extensions:
      - NamedFieldPuns
    dependencies:
      - mtl >=2.2 && <2.3

  genSQL:
    source-dirs: chapter_05
    main: genSQL.hs
    other-extensions:
      - ViewPatterns
    dependencies:
      - text >=1.2 && <1.3
      - mtl >=2.2 && <2.3

  sumList:
    source-dirs: chapter_05
    main: sumList.hs
    dependencies:
      - mtl >=2.2 && <2.3

  weapons:
    source-dirs: chapter_05
    main: weapons.hs
    dependencies:
      - mtl >=2.2 && <2.3
      - random

  dice:
    source-dirs: chapter_05
    main: dice.hs
    dependencies:
      - mtl >=2.2 && <2.3
      - random
      
  ioref:
    source-dirs: chapter_05
    main: ioref.hs

  #chapter 6
  evalrpn1:
    source-dirs: chapter_06/rpn
    main: evalrpn1.hs
    other-modules: [EvalRPN]
    dependencies:
      - mtl >=2.2 && <2.3

  rpnexcept:
    source-dirs: chapter_07/rpn
    main: EvalRPNExcept.hs
    dependencies:
      - mtl >=2.2 && <2.3
      - text
      - text-show
      
internal-libraries:
  radar-lib:
    source-dirs: chapter_02/radar
    exposed-modules: Radar
    other-modules: []
